//
//  CategoryTranslate.swift
//  stationery
//
//  Created by Codigo NOL on 19/01/2021.
//

import Foundation

class Translator {
    
    static func translate(_ categories: [ProductCategory]) -> [ProductCategory] {
//        var eng = ["2 Lines Sticky Notes", "3 Lines Sticky Notes", "3*3 Sticky Note", "3*4 Sticky Note", "3*5 Sticky Note", "4 Lines Sticky Note", "4 line book", "6\" Rulers", "999", "A blank book", "A3", "A4", "A4 Size Note (Long)", "Adhesive Products", "Adhesive Products", "Arrow Sticky Notes", "Art Range", "Bag (Thin/Thick)", "Ballpen", "Beautiful 12\" Rulers", "Beautiful 8\" Rulers", "Beautiful Bag (Large/ Small)", "Beautiful Eraser", "Beautiful Sharpeners", "Beautiful White Board", "Beauty Sticky Note", "Black Lead Eraser", "Book", "Bottle ballpen", "Box File (A4, Lg)", "CD", "CD Maker", "CD Marker Pen (Blue, Red, Black)", "COLORING PRODUCT", "CUTTING TOOL& DRAFTING", "Calculator", "Cardboard (Long/Short)", "Case box", "Cellotape", "Clear File", "Clip File", "Collage", "Color Paper A4", "Color Pencils", "Color Tape", "Coloring Book", "Coloring Product", "Colour Pencils", "Correction Pen", "Crayon Pencil", "Cutter", "DF Pen", "Double Tape", "Drawing", "Duster", "Educational Tools", "Electric Tape", "Envelope", "Eraser", "Eraser (Good/Bad)", "Exercise Book", "Faxpaper", "Files", "Five Pens line (blue, red, black)", "Flashcardsbox", "GRAPHITE PENCIL BOX", "Gifting Range", "Glitter Pen", "Glue", "Glue (Large/Medium/Small)", "Glue Sticks (Large/Medium/Small)", "Graph", "Highlighter", "Ink", "Iron Ruler-12\"", "Jelly Rulers (Short and Long) 12\"", "Lg", "Logbook (Long)", "Low viscosity ink pen", "Marker Pen", "Mathematical box", "Nippon Tape", "Notebook", "ORGANIZATION", "Office Machine", "Office Supplies", "Oil Gel Pen", "Oil Pastel", "Other Office Stuff", "PENCIL KITS", "Paper", "Paper Clips", "Paper File (Brown, Colors)", "Paper Packages", "Paper Tape", "Pencil", "Pencil (1D)", "Pencil (koTo, Uni, Pilot)", "Pencil Bag", "Pencil Lead", "Permanment Marker Pen (Blue, Red, Black)", "Picture", "Plastic Crayons", "Posco Color", "Poster Colours", "Price Tag", "Push Pen", "Rocker Pencil", "Rough Brown Paper", "Rough Paper (short /long)", "Rough White Paper", "Roung Clip (all sizes)", "Rulers", "Salary Envelope Brown (A4,Lg)", "Salary Envelope White (A4)", "Salary envelope( white, brown)", "School Accessories", "School Geometry", "School Organization", "Sharpeners", "Sharpeners ( 36, 48, 60) Bottle", "Sharpeners 24 Bottle", "Sharpeners DOMS", "Soft Pen", "Softpen (Blue, Red, Black, Green, Brown)", "Stapler", "Stapler and Punch", "Star Tape", "Stick File", "Sticker", "Sticky Notes", "Stone Ruler", "Tape", "Tempera Colours", "Toys", "Transparent Tape", "Uni Tape", "Visual Communication", "Water Color Cakes", "Water Colour Tubes", "Water Colour(Sketch)Pens", "Wax Crayons", "White Board", "White Board (Large/Small)", "White Board Marker Pen (Blue, Red, White)", "White Board Pen", "Wooden Pencil", "Writing Instrument", "Yellow Tape", "Zip File (A4, Lg, A5)", "paint brush"]
        
//        categories.forEach { cat in
//            switch cat.name {
//            case "2 Lines Sticky Notes": cat.nameMm = ""
//            case "3 Lines Sticky Notes": cat.nameMm = ""
//            case "3*3 Sticky Note": cat.nameMm = ""
//            case "3*4 Sticky Note": cat.nameMm = ""
//            case "3*5 Sticky Note": cat.nameMm = ""
//            case "4 Lines Sticky Note": cat.nameMm = ""
//            case "4 line book": cat.nameMm = ""
//            case "6\" Rulers": cat.nameMm = ""
//            case "999": cat.nameMm = ""
//            case "A blank book": cat.nameMm = ""
//            case "A3": cat.nameMm = ""
//            case "A4": cat.nameMm = ""
//            case "A4 Size Note (Long)": cat.nameMm = ""
//            case "Adhesive Products": cat.nameMm = ""
////            case "Adhesive Products": cat.nameMm = ""
//            case "Arrow Sticky Notes": cat.nameMm = ""
//            case "Art Range": cat.nameMm = ""
//            case "Bag (Thin/Thick)": cat.nameMm = ""
//            case "Ballpen": cat.nameMm = ""
//            case "Beautiful 12\" Rulers": cat.nameMm = ""
//            case "Beautiful 8\" Rulers": cat.nameMm = ""
//            case "Beautiful Bag (Large/ Small)": cat.nameMm = ""
//            case "Beautiful Eraser": cat.nameMm = ""
//            case "Beautiful Sharpeners": cat.nameMm = ""
//            case "Beautiful White Board": cat.nameMm = ""
//            case "Beauty Sticky Note": cat.nameMm = ""
//            case "Black Lead Eraser": cat.nameMm = ""
//            case "Book": cat.nameMm = ""
//            case "Bottle ballpen": cat.nameMm = ""
//            case "Box File (A4, Lg)": cat.nameMm = ""
//            case "CD": cat.nameMm = ""
//            case "CD Maker": cat.nameMm = ""
//            case "CD Marker Pen (Blue, Red, Black)": cat.nameMm = ""
//            case "COLORING PRODUCT": cat.nameMm = ""
//            case "CUTTING TOOL& DRAFTING": cat.nameMm = ""
//            case "Calculator": cat.nameMm = ""
//            case "Cardboard (Long/Short)": cat.nameMm = ""
//            case "Case box": cat.nameMm = ""
//            case "Cellotape": cat.nameMm = ""
//            case "Clear File": cat.nameMm = ""
//            case "Clip File": cat.nameMm = ""
//            case "Collage": cat.nameMm = ""
//            case "Color Paper A4": cat.nameMm = ""
//            case "Color Pencils": cat.nameMm = ""
//            case "Color Tape": cat.nameMm = ""
//            case "Coloring Book": cat.nameMm = ""
//            case "Coloring Product": cat.nameMm = ""
//            case "Colour Pencils": cat.nameMm = ""
//            case "Correction Pen": cat.nameMm = ""
//            case "Crayon Pencil": cat.nameMm = ""
//            case "Cutter": cat.nameMm = ""
//            case "DF Pen": cat.nameMm = ""
//            case "Double Tape": cat.nameMm = ""
//            case "Drawing": cat.nameMm = ""
//            case "Duster": cat.nameMm = ""
//            case "Educational Tools": cat.nameMm = ""
//            case "Electric Tape": cat.nameMm = ""
//            case "Envelope": cat.nameMm = ""
//            case "Eraser": cat.nameMm = ""
//            case "Eraser (Good/Bad)": cat.nameMm = ""
//            case "Exercise Book": cat.nameMm = ""
//            case "Faxpaper": cat.nameMm = ""
//            case "Files": cat.nameMm = ""
//            case "Five Pens line (blue, red, black)": cat.nameMm = ""
//            case "Flashcardsbox": cat.nameMm = ""
//            case "GRAPHITE PENCIL BOX": cat.nameMm = ""
//            case "Gifting Range": cat.nameMm = ""
//            case "Glitter Pen": cat.nameMm = ""
//            case "Glue": cat.nameMm = ""
//            case "Glue (Large/Medium/Small)": cat.nameMm = ""
//            case "Glue Sticks (Large/Medium/Small)": cat.nameMm = ""
//            case "Graph": cat.nameMm = ""
//            case "Highlighter": cat.nameMm = ""
//            case "Ink": cat.nameMm = ""
//            case "Iron Ruler-12\"": cat.nameMm = ""
//            case "Jelly Rulers (Short and Long) 12\"": cat.nameMm = ""
//            case "Lg": cat.nameMm = ""
//            case "Logbook (Long)": cat.nameMm = ""
//            case "Low viscosity ink pen": cat.nameMm = ""
//            case "Marker Pen": cat.nameMm = ""
//            case "Mathematical box": cat.nameMm = ""
//            case "Nippon Tape": cat.nameMm = ""
//            case "Notebook": cat.nameMm = ""
//            case "ORGANIZATION": cat.nameMm = ""
//            case "Office Machine": cat.nameMm = ""
//            case "Office Supplies": cat.nameMm = ""
//            case "Oil Gel Pen": cat.nameMm = ""
//            case "Oil Pastel": cat.nameMm = ""
//            case "Other Office Stuff": cat.nameMm = ""
//            case "PENCIL KITS": cat.nameMm = ""
//            case "Paper": cat.nameMm = ""
//            case "Paper Clips": cat.nameMm = ""
//            case "Paper File (Brown, Colors)": cat.nameMm = ""
//            case "Paper Packages": cat.nameMm = ""
//            case "Paper Tape": cat.nameMm = ""
//            case "Pencil": cat.nameMm = ""
//            case "Pencil (1D)": cat.nameMm = ""
//            case "Pencil (koTo, Uni, Pilot)": cat.nameMm = ""
//            case "Pencil Bag": cat.nameMm = ""
//            case "Pencil Lead": cat.nameMm = ""
//            case "Permanment Marker Pen (Blue, Red, Black)": cat.nameMm = ""
//            case "Picture": cat.nameMm = ""
//            case "Plastic Crayons": cat.nameMm = ""
//            case "Posco Color": cat.nameMm = ""
//            case "Poster Colours": cat.nameMm = ""
//            case "Price Tag": cat.nameMm = ""
//            case "Push Pen": cat.nameMm = ""
//            case "Rocker Pencil": cat.nameMm = ""
//            case "Rough Brown Paper": cat.nameMm = ""
//            case "Rough Paper (short /long)": cat.nameMm = ""
//            case "Rough White Paper": cat.nameMm = ""
//            case "Roung Clip (all sizes)": cat.nameMm = ""
//            case "Rulers": cat.nameMm = ""
//            case "Salary Envelope Brown (A4,Lg)": cat.nameMm = ""
//            case "Salary Envelope White (A4)": cat.nameMm = ""
//            case "Salary envelope( white, brown)": cat.nameMm = ""
//            case "School Accessories": cat.nameMm = ""
//            case "School Geometry": cat.nameMm = ""
//            case "School Organization": cat.nameMm = ""
//            case "Sharpeners": cat.nameMm = ""
//            case "Sharpeners ( 36, 48, 60) Bottle": cat.nameMm = ""
//            case "Sharpeners 24 Bottle": cat.nameMm = ""
//            case "Sharpeners DOMS": cat.nameMm = ""
//            case "Soft Pen": cat.nameMm = ""
//            case "Softpen (Blue, Red, Black, Green, Brown)": cat.nameMm = ""
//            case "Stapler": cat.nameMm = ""
//            case "Stapler and Punch": cat.nameMm = ""
//            case "Star Tape": cat.nameMm = ""
//            case "Stick File": cat.nameMm = ""
//            case "Sticker": cat.nameMm = ""
//            case "Sticky Notes": cat.nameMm = ""
//            case "Stone Ruler": cat.nameMm = ""
//            case "Tape": cat.nameMm = ""
//            case "Tempera Colours": cat.nameMm = ""
//            case "Toys": cat.nameMm = ""
//            case "Transparent Tape": cat.nameMm = ""
//            case "Uni Tape": cat.nameMm = ""
//            case "Visual Communication": cat.nameMm = ""
//            case "Water Color Cakes": cat.nameMm = ""
//            case "Water Colour Tubes": cat.nameMm = ""
//            case "Water Colour(Sketch)Pens": cat.nameMm = ""
//            case "Wax Crayons": cat.nameMm = ""
//            case "White Board": cat.nameMm = ""
//            case "White Board (Large/Small)": cat.nameMm = ""
//            case "White Board Marker Pen (Blue, Red, White)": cat.nameMm = ""
//            case "White Board Pen": cat.nameMm = ""
//            case "Wooden Pencil": cat.nameMm = ""
//            case "Writing Instrument": cat.nameMm = ""
//            case "Yellow Tape": cat.nameMm = ""
//            case "Zip File (A4, Lg, A5)": cat.nameMm = ""
//            case "paint brush": cat.nameMm = ""
//            default: cat.nameMm = cat.name
//            }
//        }
        
        return categories
    }
}
